language: cpp
sudo: false

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
jobs:
  include:
    - stage: compile
      script: |
                mkdir build
                cd build
                cmake ..
                make -j 2

    - stage: test
      script: |
                mkdir build
                cd build
                cmake ..
                make -j 2
                test/vibeam_test

stages:
  - compile
  - test
